package me.paranoid.wifikill;

/* JADX INFO: This class is generated by JADX */
public final class R {

    public static final class anim {
        public static final int fragment_slide_left_enter = 0x7f040000;
        public static final int fragment_slide_left_exit = 0x7f040001;
        public static final int fragment_slide_right_enter = 0x7f040002;
        public static final int fragment_slide_right_exit = 0x7f040003;
        public static final int slide_left = 0x7f040004;
        public static final int slide_right = 0x7f040005;
    }

    public static final class drawable {
        public static final int action_bar = 0x7f020000;
        public static final int background = 0x7f020001;
        public static final int background_killed = 0x7f020002;
        public static final int background_texture = 0x7f020003;
        public static final int background_texture_light = 0x7f020004;
        public static final int bg = 0x7f020005;
        public static final int bg_light = 0x7f020006;
        public static final int bg_stripes_dark = 0x7f020007;
        public static final int ic_launcher = 0x7f020008;
        public static final int ic_menu_refresh = 0x7f020009;
        public static final int icon = 0x7f02000a;
        public static final int killed = 0x7f02000b;
        public static final int shadow_bottom = 0x7f02000c;
        public static final int shadow_left = 0x7f02000d;
        public static final int shadow_top = 0x7f02000e;
    }

    public static final class id {
        public static final int RelativeLayout1 = 0x7f090000;
        public static final int top_bar = 0x7f090001;
        public static final int shadow = 0x7f090002;
        public static final int name = 0x7f090003;
        public static final int line3 = 0x7f090004;
        public static final int RelativeLayout2 = 0x7f090005;
        public static final int detail_bar = 0x7f090006;
        public static final int url = 0x7f090007;
        public static final int adView = 0x7f090008;
        public static final int view1 = 0x7f090009;
        public static final int attach_switch = 0x7f09000a;
        public static final int kill_switch = 0x7f09000b;
        public static final int detail_ip = 0x7f09000c;
        public static final int line = 0x7f09000d;
        public static final int shadow_top = 0x7f09000e;
        public static final int shadow_left = 0x7f09000f;
        public static final int killed_layout = 0x7f090010;
        public static final int info = 0x7f090011;
        public static final int state = 0x7f090012;
        public static final int killed_shadow = 0x7f090013;
        public static final int ip = 0x7f090014;
        public static final int nbname = 0x7f090015;
        public static final int net_usage = 0x7f090016;
        public static final int textView1 = 0x7f090017;
        public static final int up = 0x7f090018;
        public static final int textView3 = 0x7f090019;
        public static final int down = 0x7f09001a;
        public static final int vendor = 0x7f09001b;
        public static final int hwaddr = 0x7f09001c;
        public static final int progressBar = 0x7f09001d;
        public static final int spinner = 0x7f09001e;
        public static final int progressBar2 = 0x7f09001f;
        public static final int message = 0x7f090020;
        public static final int view4 = 0x7f090021;
        public static final int view3 = 0x7f090022;
        public static final int device_list = 0x7f090023;
        public static final int status_bar = 0x7f090024;
        public static final int view2 = 0x7f090025;
        public static final int search_progress = 0x7f090026;
        public static final int top_line = 0x7f090027;
        public static final int fragment_container = 0x7f090028;
        public static final int details = 0x7f090029;
        public static final int kill_all = 0x7f09002a;
        public static final int attach_all = 0x7f09002b;
        public static final int online = 0x7f09002c;
        public static final int offline = 0x7f09002d;
        public static final int date = 0x7f09002e;
        public static final int path = 0x7f09002f;
        public static final int host = 0x7f090030;
        public static final int menu_power = 0x7f090031;
        public static final int menu_refresh = 0x7f090032;
        public static final int menu_search = 0x7f090033;
        public static final int menu_preferences = 0x7f090034;
        public static final int menu_help = 0x7f090035;
        public static final int menu_about = 0x7f090036;
    }

    public static final class layout {
        public static final int details = 0x7f030000;
        public static final int device = 0x7f030001;
        public static final int fragment_kill_revive = 0x7f030002;
        public static final int main = 0x7f030003;
        public static final int status_bar = 0x7f030004;
        public static final int url_child_view = 0x7f030005;
        public static final int url_group_view = 0x7f030006;
    }

    public static final class menu {
        public static final int main = 0x7f080000;
    }

    public static final class string {
        public static final int app_name = 0x7f060000;
        public static final int hello = 0x7f060001;
        public static final int kill_all_switch = 0x7f060002;
        public static final int example_ip = 0x7f060003;
        public static final int example_device_name = 0x7f060004;
        public static final int device_label_up = 0x7f060005;
        public static final int example_1mb = 0x7f060006;
        public static final int device_label_down = 0x7f060007;
        public static final int example_device_vendor = 0x7f060008;
        public static final int example_http_link = 0x7f060009;
        public static final int hint_device_name = 0x7f06000a;
        public static final int switch_kill = 0x7f06000b;
        public static final int example_10mb = 0x7f06000c;
        public static final int statusbar_0 = 0x7f06000d;
        public static final int attach = 0x7f06000e;
        public static final int attach_to_all = 0x7f06000f;
        public static final int killed = 0x7f060010;
        public static final int example_time = 0x7f060011;
        public static final int example_url_path = 0x7f060012;
        public static final int example_url_host = 0x7f060013;
    }

    public static final class style {
        public static final int AppTheme = 0x7f070000;
    }

    public static final class xml {
        public static final int preferences = 0x7f050000;
    }
}
